In [73]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [74]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, : -1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[[2.3  1.97 1.8  1.56]
 [1.81 1.68 1.57 1.86]
 [3.07 3.   2.75 3.21]
 ...
 [3.31 3.25 3.44 3.52]
 [3.44 3.35 3.5  3.5 ]
 [3.18 3.05 3.05 3.27]]


In [ ]:
print(y)

['Tidak' 'Tidak' 'Tidak' ... 'Ya' 'Ya' 'Ya']


In [75]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:4])
x[:, 1:4] = imputer.transform(x[:, 1:4])

In [ ]:
print(x)

  (0, 32)	1.0
  (0, 172)	1.97
  (0, 173)	1.8
  (0, 174)	1.56
  (1, 12)	1.0
  (1, 172)	1.68
  (1, 173)	1.57
  (1, 174)	1.86
  (2, 101)	1.0
  (2, 172)	3.0
  (2, 173)	2.75
  (2, 174)	3.21
  (3, 66)	1.0
  (3, 172)	2.33
  (3, 173)	2.61
  (3, 174)	1.98
  (4, 111)	1.0
  (4, 172)	3.02
  (4, 173)	3.28
  (4, 174)	2.96
  (5, 110)	1.0
  (5, 172)	3.45
  (5, 173)	3.02
  (5, 174)	3.06
  (6, 67)	1.0
  :	:
  (1680, 174)	3.38
  (1681, 114)	1.0
  (1681, 172)	3.26
  (1681, 173)	3.36
  (1681, 174)	3.5
  (1682, 101)	1.0
  (1682, 172)	3.04
  (1682, 173)	3.39
  (1682, 174)	3.55
  (1683, 123)	1.0
  (1683, 172)	3.22
  (1683, 173)	3.33
  (1683, 174)	3.68
  (1684, 125)	1.0
  (1684, 172)	3.25
  (1684, 173)	3.44
  (1684, 174)	3.52
  (1685, 138)	1.0
  (1685, 172)	3.35
  (1685, 173)	3.5
  (1685, 174)	3.5
  (1686, 112)	1.0
  (1686, 172)	3.05
  (1686, 173)	3.05
  (1686, 174)	3.27


In [68]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [69]:
print(x)

  (0, 32)	1.0
  (0, 172)	1.97
  (0, 173)	1.8
  (0, 174)	1.56
  (1, 12)	1.0
  (1, 172)	1.68
  (1, 173)	1.57
  (1, 174)	1.86
  (2, 101)	1.0
  (2, 172)	3.0
  (2, 173)	2.75
  (2, 174)	3.21
  (3, 66)	1.0
  (3, 172)	2.33
  (3, 173)	2.61
  (3, 174)	1.98
  (4, 111)	1.0
  (4, 172)	3.02
  (4, 173)	3.28
  (4, 174)	2.96
  (5, 110)	1.0
  (5, 172)	3.45
  (5, 173)	3.02
  (5, 174)	3.06
  (6, 67)	1.0
  :	:
  (1680, 174)	3.38
  (1681, 114)	1.0
  (1681, 172)	3.26
  (1681, 173)	3.36
  (1681, 174)	3.5
  (1682, 101)	1.0
  (1682, 172)	3.04
  (1682, 173)	3.39
  (1682, 174)	3.55
  (1683, 123)	1.0
  (1683, 172)	3.22
  (1683, 173)	3.33
  (1683, 174)	3.68
  (1684, 125)	1.0
  (1684, 172)	3.25
  (1684, 173)	3.44
  (1684, 174)	3.52
  (1685, 138)	1.0
  (1685, 172)	3.35
  (1685, 173)	3.5
  (1685, 174)	3.5
  (1686, 112)	1.0
  (1686, 172)	3.05
  (1686, 173)	3.05
  (1686, 174)	3.27


In [79]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [80]:
print(y)

[0 0 0 ... 1 1 1]


In [81]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [82]:
print(x_train)

[[2.95 2.95 3.24 3.19]
 [3.35 3.14 3.28 3.31]
 [3.6  3.65 3.49 3.36]
 ...
 [3.65 3.76 3.2  3.37]
 [2.87 3.01 3.16 3.1 ]
 [3.07 3.27 3.38 3.26]]


In [83]:
print(x_test)

[[3.45 3.25 3.65 3.61]
 [3.43 3.22 3.06 3.16]
 [2.89 3.09 3.06 3.26]
 ...
 [3.09 3.35 3.52 3.56]
 [3.03 3.59 3.47 3.31]
 [3.21 3.27 3.31 3.52]]


In [84]:
print(y_train)

[1 0 1 ... 1 0 1]


In [ ]:
print(y_test)

['Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya'
 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya'
 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Tidak' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya'
 'Tidak' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya'
 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya'
 'Ya' 'Ya' 'Tidak' 'Tidak' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Tidak'
 'Ya' 'Ya' 'Ya' 'Ya' 'Tidak' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya'
 'Tidak' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Tidak'
 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Tidak' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya'
 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Tidak'
 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Tidak' 'Ya' 'Tidak' 'Tidak' 'Ya' 'Ya' 'Ya'
 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya'
 'Tidak' 'Tidak' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Tidak' 'Ya' 'Ya' 'Ya'
 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya' 'Ya

In [87]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 1:] = sc.fit_transform(x_train[:, 1:])
x_test[:, 1:] = sc.transform(x_test[:, 1:])

In [88]:
print(x_train)

[[ 2.95       -0.4996301  -0.04171619 -0.23322039]
 [ 3.35       -0.07945755  0.07626105  0.06503934]
 [ 3.6         1.04837405  0.69564157  0.18931423]
 ...
 [ 3.65        1.29163184 -0.15969344  0.21416921]
 [ 2.87       -0.36694403 -0.27767068 -0.45691519]
 [ 3.07        0.20802894  0.37120416 -0.05923555]]
